name: "CBus MQTT Bridge"
version: "1.0.0"
slug: "cbusmqtt"
description: "An improved C-Bus to MQTT bridge for Home Assistant with better state tracking"
url: "https://github.com/haroldjcarp/MQTTWD"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  cbus:
    interface: "tcp"
    host: "192.168.1.100"
    port: 10001
    network: 254
    application: 56
    monitoring:
      enabled: true
      poll_interval: 30
      max_retries: 3
      timeout: 5
  mqtt:
    broker: "core-mosquitto"
    port: 1883
    username: "homeassistant"
    password: "password"
    topics:
      command: "cbus/command"
      state: "cbus/state"
    keepalive: 60
    reconnect_delay: 5
  discovery:
    enabled: true
    prefix: "homeassistant"
    auto_discovery: true
  logging:
    level: "INFO"
schema:
  cbus:
    interface: "list(tcp|serial|pci)"
    host: "str?"
    port: "int?"
    serial_port: "str?"
    pci_device: "str?"
    network: "int"
    application: "int"
    monitoring:
      enabled: "bool"
      poll_interval: "int"
      max_retries: "int"
      timeout: "int"
  mqtt:
    broker: "str"
    port: "int"
    username: "str?"
    password: "str?"
    topics:
      command: "str"
      state: "str"
    keepalive: "int"
    reconnect_delay: "int"
  discovery:
    enabled: "bool"
    prefix: "str"
    auto_discovery: "bool"
  logging:
    level: "list(DEBUG|INFO|WARNING|ERROR|CRITICAL)"
    file: "str?"
services:
  - mqtt:need
ports:
  8080/tcp: null
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyACM0
  - /dev/ttyACM1
udev: true
uart: true
usb: true
host_network: true
image: "ghcr.io/haroldjcarp/cbusmqtt-{arch}" 